version: '3.7'

services:
    web:
        container_name: react_cli
        build: .
        restart: always
        ports:
            - 9200:80
        volumes:
            - ./:/app
        environment:
            VIRTUAL_HOST: reactcli.org,www.reactcli.org
            LETSENCRYPT_HOST: reactcli.org,www.reactcli.org
            LETSENCRYPT_EMAIL: contact@reactcli.org

networks:
    default:
        external:
            name: nginx-proxy
