name: CI/CD

on:
    push:
        branches:
            - master

jobs:
    build:
        name: Build and Deploy
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Setup Node.js 16.13.1
              uses: actions/setup-node@v1
              with:
                  node-version: '16.13.1'

            - name: Install dependencies
              run: npm install

            - name: Build
              run: npm run build

            - name: Copy to server
              uses: appleboy/scp-action@master
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  password: ${{ secrets.PASSWORD }}
                  port: ${{ secrets.PORT }}
                  source: 'out, nginx.conf, dockerfile, docker-compose.yml'
                  target: 'react-cli-site'

            - name: Run docker compose
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  password: ${{ secrets.PASSWORD }}
                  port: ${{ secrets.PORT }}
                  rm: true
                  script: |
                      cd react-cli-site
                      docker-compose up -d --build
